### ISSUE TITLE
size mismatch between gt and prediction

### ISSUE THREAD

**Issue by EunjinSon1** [HalleyJiang/RomniStereo#2]
Hi, thank you for your great work.

I tried to train a model using your code on the Omnithings dataset, but I encountered the following error at i_loss = (preds[i] - gt).abs():
The size of tensor a (80) must match the size of tensor b (160) at non-singleton dimension 2

This error seems to occur because the shape of 'grids' changes when input to net().
for example,

train.py
def train():
   ...
   print(grids[0].shape) -> torch.Size([80, 320, 96, 2])
   predictions = net(imgs, grids, opts.train_iters)
   ...

network.py
class ROmniStereo():
  def forward:
     print(grids[0].shape) -> torch.Size([40, 320, 96, 2])

How can I solve this? thank you

**Comment by HalleyJiang** [comment]
I don't know what happened in your running environment. I just debugged the code again and inside the _forward_, the shape of the grid is still [80, 320, 96, 2]. Please carefully check your environment.
